name: Spring Petclinic CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    uses: saikrishna8763/github-templates/.github/workflows/build.yaml@main
    with:
      java-version: '17'
      build-tool: 'gradle'
      service-name: 'petclinic'
      project-path: '.'

  test:
    needs: build
    uses: saikrishna8763/github-templates/.github/workflows/test.yaml@main
    with:
      java-version: '17'
      build-tool: 'gradle'
      project-path: '.'

  sonar:
    needs: test
    uses: saikrishna8763/github-templates/.github/workflows/sonar.yaml@main
    with:
      java-version: '17'
      build-tool: 'gradle'
      sonar-project-key: 'java-gradle'
      project-path: '.'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docker:
    needs: sonar
    uses: saikrishna8763/github-templates/.github/workflows/docker.yaml@main
    with:
      image-name: spring-petclinic
      project-path: '.'
    secrets:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      

